import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>
            <h1>My Portfolio</h1>
            <nav>
              <Link href="/">Home</Link>
              <Link href="/tutorials">Tutorials</Link>
              <Link href="/career-journal">Career Journal</Link>
            </nav>
            <div>
              <button id="mobile-menu-button">
                <span>Open main menu</span>
                <svg fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24" aria-hidden="true">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
          <nav id="mobile-menu">
            <Link href="/">Home</Link>
            <Link href="/tutorials">Tutorials</Link>
            <Link href="/career-journal">Career Journal</Link>
          </nav>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <div>
            &copy; {new Date().getFullYear()} Zeus Zaragoza-Gildo. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
